// _MainMenu_EOArchive_English.java
// Generated by EnterpriseObjects palette at Monday, July 4, 2005 12:33:44 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MainMenu_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ArrayController _arrayController0;
    GridStufferAppDelegate _gridStufferAppDelegate0;
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector10, _iBHelpConnector11, _iBHelpConnector2, _iBHelpConnector3, _iBHelpConnector4, _iBHelpConnector5, _iBHelpConnector6, _iBHelpConnector7, _iBHelpConnector8, _iBHelpConnector9;
    ImageCell _imageCell0;
    LevelIndicatorCell _levelIndicatorCell0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1, _nsTableView2, _nsTableView3;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn10, _eoTableColumn2, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8, _eoTableColumn9;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField2, _eoTextField3, _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField18, _nsTextField19, _nsTextField2, _nsTextField20, _nsTextField21, _nsTextField22, _nsTextField23, _nsTextField24, _nsTextField25, _nsTextField26, _nsTextField27, _nsTextField28, _nsTextField29, _nsTextField3, _nsTextField30, _nsTextField31, _nsTextField32, _nsTextField33, _nsTextField34, _nsTextField35, _nsTextField36, _nsTextField37, _nsTextField38, _nsTextField39, _nsTextField4, _nsTextField40, _nsTextField41, _nsTextField42, _nsTextField43, _nsTextField44, _nsTextField45, _nsTextField46, _nsTextField47, _nsTextField48, _nsTextField49, _nsTextField5, _nsTextField50, _nsTextField51, _nsTextField52, _nsTextField53, _nsTextField54, _nsTextField55, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsView0, _nsView1, _nsView2, _nsView3, _nsView4, _nsView5;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0, _nsNumberFormatter1, _nsNumberFormatter10, _nsNumberFormatter11, _nsNumberFormatter12, _nsNumberFormatter13, _nsNumberFormatter14, _nsNumberFormatter15, _nsNumberFormatter16, _nsNumberFormatter17, _nsNumberFormatter18, _nsNumberFormatter19, _nsNumberFormatter2, _nsNumberFormatter3, _nsNumberFormatter4, _nsNumberFormatter5, _nsNumberFormatter6, _nsNumberFormatter7, _nsNumberFormatter8, _nsNumberFormatter9;
    javax.swing.JCheckBox _jCheckBox0, _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8;
    javax.swing.JPanel _nsView6, _nsView7;
    javax.swing.JTabbedPane _nsTabView0;

    public _MainMenu_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsNumberFormatter19 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _imageCell0 = (ImageCell)_registered(new ImageCell(), "");
        _nsNumberFormatter18 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter17 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter16 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter15 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _levelIndicatorCell0 = (LevelIndicatorCell)_registered(new LevelIndicatorCell(), "");
        _jCheckBox0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _nsNumberFormatter14 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0%;-0%"), "");
        _nsNumberFormatter13 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0%;-0%"), "");
        _nsNumberFormatter12 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter11 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter10 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _nsNumberFormatter9 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _nsNumberFormatter8 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0%;-0%"), "");
        _nsNumberFormatter7 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter6 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter5 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsNumberFormatter4 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0%;-0%"), "");
        _nsNumberFormatter3 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsNumberFormatter2 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsNumberFormatter1 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _eoTableColumn10 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn9 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView3 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsView5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField55 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField54 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField53 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsTextField52 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField51 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField112111");
        _nsTextField50 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12111");
        _nsTextField49 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _nsTextField48 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11211");
        _nsTextField47 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1211");
        _nsTextField46 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111");
        _nsTextField45 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1121");
        _nsTextField44 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField121");
        _nsTextField43 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111");
        _nsTextField42 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField112");
        _nsTextField41 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        _nsTextField40 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField39 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField38 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextField37 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsView4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsButton8 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Nothing: no file, no stdout and no stderr"), "NSButton41221");
        _nsButton7 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Stderr is non-empty"), "NSButton41211");
        _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Stderr is empty"), "NSButton4122");
        _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Stdout is non-empty"), "NSButton4121");
        _nsButton4 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Stdout is empty"), "NSButton412");
        _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("All empty"), "NSButton4111");
        _nsButton2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("One file empty"), "NSButton411");
        _nsButton1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("No file created"), "NSButton41");
        _nsTextField36 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111321311");
        _nsTextField35 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111311131");
        _nsTextField34 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField31");
        _nsTextField33 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111132131");
        _nsTextField32 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111131113");
        _nsTextField31 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        _nsTextField30 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113213");
        _nsView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField29 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111132121");
        _nsTextField28 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113111221");
        _iBHelpConnector11 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField27 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2321");
        _nsTextField26 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111311122");
        _iBHelpConnector10 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField25 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField232");
        _nsTextField24 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113212");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113111231");
        _nsTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111311123");
        _nsTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1312");
        _iBHelpConnector9 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField233");
        _nsTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111131112");
        _nsTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField131");
        _iBHelpConnector8 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField23");
        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13");
        _iBHelpConnector7 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111131111");
        _iBHelpConnector6 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111311121");
        _iBHelpConnector5 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField231");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1311");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBHelpConnector4 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Cache files in memory"), "NSButton4");
        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113111");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111321");
        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113214");
        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111311");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111132");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111131");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111113");
        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.metaJobInspectorPanel")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Job inspector");
        }

        _nsView7 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.jobArrayController")) != null)) {
            _arrayController0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ArrayController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_arrayController0");
        } else {
            _arrayController0 = (ArrayController)_registered(new ArrayController(), "metaJobs");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate")) != null)) {
            _gridStufferAppDelegate0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (GridStufferAppDelegate)replacement;
            _replacedObjects.setObjectForKey(replacement, "_gridStufferAppDelegate0");
        } else {
            _gridStufferAppDelegate0 = (GridStufferAppDelegate)_registered(new GridStufferAppDelegate(), "GridStufferAppDelegate");
        }

        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate.window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Job list");
        }

        _nsView6 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "unhideAllApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hide", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hideOtherApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "orderFrontStandardAboutPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "terminate", ), ""));

        if (_replacedObjects.objectForKey("_gridStufferAppDelegate0") == null) {
            _connect(_owner(), _gridStufferAppDelegate0, "delegate");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_eoTextField3, "Lucida Grande", 11, Font.PLAIN);
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "cut", ), ""));
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performFindPanelAction", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "arrangeInFront", ), ""));
        
        
        
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "showHelp", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performZoom", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performMiniaturize", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "toggleContinuousSpellChecking", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "selectAll", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "checkSpelling", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "delete", ), ""));
        _setFontForComponent(_jCheckBox0, "Lucida Grande", 12, Font.PLAIN);
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "pasteAsPlainText", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "centerSelectionInVisibleArea", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "paste", ), ""));
        
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "print", ), ""));
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performFindPanelAction", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "copy", ), ""));
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performFindPanelAction", ), ""));
        
        
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "performFindPanelAction", ), ""));
        
        
        _setFontForComponent(_eoTextField2, "Lucida Grande", 11, Font.PLAIN);
        
        
        _setFontForComponent(_eoTextField1, "Lucida Grande", 11, Font.PLAIN);
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "runPageLayout", ), ""));
        _setFontForComponent(_eoTextField0, "Lucida Grande", 11, Font.PLAIN);
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "redo", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "showGuessPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "undo", ), ""));
        
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_gridStufferAppDelegate0, "startMetaJob", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_gridStufferAppDelegate0, "startMetaJob", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_gridStufferAppDelegate0, "insertNewMetaJob", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_gridStufferAppDelegate0, "showServerListWindow", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame1, "makeKeyAndOrderFront", ), ""));
        _eoTableColumn10.setMinWidth(40);
        _eoTableColumn10.setMaxWidth(1000);
        _eoTableColumn10.setPreferredWidth(336);
        _eoTableColumn10.setWidth(336);
        _eoTableColumn10.setResizable(true);
        _eoTableColumn10.setHeaderValue("");
        if ((_eoTableColumn10.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn10.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn9.setMinWidth(40);
        _eoTableColumn9.setMaxWidth(1000);
        _eoTableColumn9.setPreferredWidth(40);
        _eoTableColumn9.setWidth(40);
        _eoTableColumn9.setResizable(true);
        _eoTableColumn9.setHeaderValue("");
        if ((_eoTableColumn9.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn9.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView3.table().addColumn(_eoTableColumn9);
        _nsTableView3.table().addColumn(_eoTableColumn10);
        _setFontForComponent(_nsTableView3.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView3.table().setRowHeight(20);
        if (!(_nsView5.getLayout() instanceof EOViewLayout)) { _nsView5.setLayout(new EOViewLayout()); }
        _nsTableView3.setSize(384, 295);
        _nsTableView3.setLocation(20, 20);
        ((EOViewLayout)_nsView5.getLayout()).setAutosizingMask(_nsTableView3, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView5.add(_nsTableView3);
        _setFontForComponent(_nsTextField55, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField55.setEditable(false);
        _nsTextField55.setOpaque(false);
        _nsTextField55.setText("D`");
        _nsTextField55.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField55.setSelectable(false);
        _nsTextField55.setEnabled(true);
        _nsTextField55.setBorder(null);
        _setFontForComponent(_nsTextField54, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField54.setEditable(false);
        _nsTextField54.setOpaque(false);
        _nsTextField54.setText("C");
        _nsTextField54.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField54.setSelectable(false);
        _nsTextField54.setEnabled(true);
        _nsTextField54.setBorder(null);
        _setFontForComponent(_nsTextField53, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField53.setEditable(false);
        _nsTextField53.setOpaque(false);
        _nsTextField53.setText("S");
        _nsTextField53.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField53.setSelectable(false);
        _nsTextField53.setEnabled(true);
        _nsTextField53.setBorder(null);
        _setFontForComponent(_nsTextField52, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField52.setEditable(false);
        _nsTextField52.setOpaque(false);
        _nsTextField52.setText("100%");
        _nsTextField52.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField52.setSelectable(false);
        _nsTextField52.setEnabled(true);
        _nsTextField52.setBorder(null);
        _setFontForComponent(_nsTextField51, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField51.setEditable(false);
        _nsTextField51.setOpaque(false);
        _nsTextField51.setText("1,000,000");
        _nsTextField51.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField51.setSelectable(false);
        _nsTextField51.setEnabled(true);
        _nsTextField51.setBorder(null);
        _setFontForComponent(_nsTextField50, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField50.setEditable(false);
        _nsTextField50.setOpaque(false);
        _nsTextField50.setText("Dismissed");
        _nsTextField50.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField50.setSelectable(false);
        _nsTextField50.setEnabled(true);
        _nsTextField50.setBorder(null);
        _setFontForComponent(_nsTextField49, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField49.setEditable(false);
        _nsTextField49.setOpaque(false);
        _nsTextField49.setText("100%");
        _nsTextField49.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField49.setSelectable(false);
        _nsTextField49.setEnabled(true);
        _nsTextField49.setBorder(null);
        _setFontForComponent(_nsTextField48, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField48.setEditable(false);
        _nsTextField48.setOpaque(false);
        _nsTextField48.setText("1,000,000");
        _nsTextField48.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField48.setSelectable(false);
        _nsTextField48.setEnabled(true);
        _nsTextField48.setBorder(null);
        _setFontForComponent(_nsTextField47, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField47.setEditable(false);
        _nsTextField47.setOpaque(false);
        _nsTextField47.setText("Completed");
        _nsTextField47.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField47.setSelectable(false);
        _nsTextField47.setEnabled(true);
        _nsTextField47.setBorder(null);
        _setFontForComponent(_nsTextField46, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField46.setEditable(false);
        _nsTextField46.setOpaque(false);
        _nsTextField46.setText("100%");
        _nsTextField46.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField46.setSelectable(false);
        _nsTextField46.setEnabled(true);
        _nsTextField46.setBorder(null);
        _setFontForComponent(_nsTextField45, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField45.setEditable(false);
        _nsTextField45.setOpaque(false);
        _nsTextField45.setText("1,000,000");
        _nsTextField45.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField45.setSelectable(false);
        _nsTextField45.setEnabled(true);
        _nsTextField45.setBorder(null);
        _setFontForComponent(_nsTextField44, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField44.setEditable(false);
        _nsTextField44.setOpaque(false);
        _nsTextField44.setText("Submitted");
        _nsTextField44.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField44.setSelectable(false);
        _nsTextField44.setEnabled(true);
        _nsTextField44.setBorder(null);
        _setFontForComponent(_nsTextField43, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField43.setEditable(false);
        _nsTextField43.setOpaque(false);
        _nsTextField43.setText("100%");
        _nsTextField43.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField43.setSelectable(false);
        _nsTextField43.setEnabled(true);
        _nsTextField43.setBorder(null);
        _setFontForComponent(_nsTextField42, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField42.setEditable(false);
        _nsTextField42.setOpaque(false);
        _nsTextField42.setText("1,000,000");
        _nsTextField42.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField42.setSelectable(false);
        _nsTextField42.setEnabled(true);
        _nsTextField42.setBorder(null);
        _setFontForComponent(_nsTextField41, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField41.setEditable(false);
        _nsTextField41.setOpaque(false);
        _nsTextField41.setText("Pending");
        _nsTextField41.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField41.setSelectable(false);
        _nsTextField41.setEnabled(true);
        _nsTextField41.setBorder(null);
        _setFontForComponent(_nsTextField40, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField40.setEditable(false);
        _nsTextField40.setOpaque(false);
        _nsTextField40.setText("1,000,000");
        _nsTextField40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField40.setSelectable(false);
        _nsTextField40.setEnabled(true);
        _nsTextField40.setBorder(null);
        _setFontForComponent(_nsTextField39, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField39.setEditable(false);
        _nsTextField39.setOpaque(false);
        _nsTextField39.setText("Total");
        _nsTextField39.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField39.setSelectable(false);
        _nsTextField39.setEnabled(true);
        _nsTextField39.setBorder(null);
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsTextField39.setSize(32, 14);
        _nsTextField39.setLocation(67, 14);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField39, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField39);
        _nsTextField40.setSize(96, 14);
        _nsTextField40.setLocation(141, 14);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField40, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField40);
        _nsTextField41.setSize(47, 14);
        _nsTextField41.setLocation(67, 32);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField41, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField41);
        _nsTextField42.setSize(96, 14);
        _nsTextField42.setLocation(141, 32);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField42, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField42);
        _nsTextField43.setSize(63, 14);
        _nsTextField43.setLocation(254, 32);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField43, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField43);
        _nsTextField44.setSize(59, 14);
        _nsTextField44.setLocation(67, 50);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField44, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField44);
        _nsTextField45.setSize(96, 14);
        _nsTextField45.setLocation(141, 50);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField45, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField45);
        _nsTextField46.setSize(63, 14);
        _nsTextField46.setLocation(254, 50);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField46, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField46);
        _nsTextField47.setSize(63, 14);
        _nsTextField47.setLocation(67, 68);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField47, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField47);
        _nsTextField48.setSize(96, 14);
        _nsTextField48.setLocation(141, 68);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField48, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField48);
        _nsTextField49.setSize(63, 14);
        _nsTextField49.setLocation(254, 68);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField49, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField49);
        _nsTextField50.setSize(59, 14);
        _nsTextField50.setLocation(67, 86);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField50, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField50);
        _nsTextField51.setSize(96, 14);
        _nsTextField51.setLocation(141, 86);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField51, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField51);
        _nsTextField52.setSize(63, 14);
        _nsTextField52.setLocation(254, 86);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField52, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsTextField52);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(386, 114);
        _nsBox5.setLocation(2, 15);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Commands", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField38, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField38.setEditable(false);
        _nsTextField38.setOpaque(true);
        _nsTextField38.setText("");
        _nsTextField38.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField38.setSelectable(true);
        _nsTextField38.setEnabled(true);
        _setFontForComponent(_nsTextField37, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField37.setEditable(false);
        _nsTextField37.setOpaque(true);
        _nsTextField37.setText("");
        _nsTextField37.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField37.setSelectable(true);
        _nsTextField37.setEnabled(true);
        _eoTableColumn8.setMinWidth(25);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(25);
        _eoTableColumn8.setWidth(25);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("");
        if ((_eoTableColumn8.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn8.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn8.setCellRenderer(renderer);
        }
        if ((_eoTableColumn8.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn8.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }
        _eoTableColumn7.setMinWidth(25);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(25);
        _eoTableColumn7.setWidth(25);
        _eoTableColumn7.setResizable(false);
        _eoTableColumn7.setHeaderValue("");
        if ((_eoTableColumn7.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn7.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn7.setCellRenderer(renderer);
        }
        if ((_eoTableColumn7.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn7.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }
        _eoTableColumn6.setMinWidth(25);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(25);
        _eoTableColumn6.setWidth(25);
        _eoTableColumn6.setResizable(false);
        _eoTableColumn6.setHeaderValue("");
        if ((_eoTableColumn6.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn6.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn6.setCellRenderer(renderer);
        }
        if ((_eoTableColumn6.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn6.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }
        _eoTableColumn5.setMinWidth(20);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(20);
        _eoTableColumn5.setWidth(20);
        _eoTableColumn5.setResizable(false);
        _eoTableColumn5.setHeaderValue("");
        if ((_eoTableColumn5.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn5.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView2.table().addColumn(_eoTableColumn5);
        _nsTableView2.table().addColumn(_eoTableColumn6);
        _nsTableView2.table().addColumn(_eoTableColumn7);
        _nsTableView2.table().addColumn(_eoTableColumn8);
        _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView2.table().setRowHeight(20);
        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsTableView2.setSize(123, 145);
        _nsTableView2.setLocation(20, 170);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.MaxXMargin | EOViewLayout.HeightSizable);
        _nsView4.add(_nsTableView2);
        _nsTextField37.setSize(253, 37);
        _nsTextField37.setLocation(152, 156);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField37, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsTextField37);
        _nsTextField38.setSize(253, 114);
        _nsTextField38.setLocation(152, 201);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField38, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView4.add(_nsTextField38);
        _nsBox4.setSize(390, 131);
        _nsBox4.setLocation(17, 10);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsBox4);
        _nsTextField53.setSize(17, 14);
        _nsTextField53.setLocation(53, 155);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField53, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsTextField53);
        _nsTextField54.setSize(17, 14);
        _nsTextField54.setLocation(81, 155);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField54, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsTextField54);
        _nsTextField55.setSize(17, 14);
        _nsTextField55.setLocation(110, 155);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTextField55, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView4.add(_nsTextField55);
        _setFontForComponent(_nsButton8, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton7, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton6, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton5, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton4, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton3, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton2, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField36, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField36.setEditable(false);
        _nsTextField36.setOpaque(false);
        _nsTextField36.setText("Consider command failed if one of the following is true:");
        _nsTextField36.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField36.setSelectable(false);
        _nsTextField36.setEnabled(true);
        _nsTextField36.setBorder(null);
        _setFontForComponent(_nsTextField35, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField35.setEditable(false);
        _nsTextField35.setOpaque(false);
        _nsTextField35.setText("failures");
        _nsTextField35.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField35.setSelectable(true);
        _nsTextField35.setEnabled(true);
        _nsTextField35.setBorder(null);
        _setFontForComponent(_nsTextField34, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField34.setEditable(true);
        _nsTextField34.setOpaque(true);
        _nsTextField34.setText("");
        _nsTextField34.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField34.setSelectable(true);
        _nsTextField34.setEnabled(true);
        _setFontForComponent(_nsTextField33, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField33.setEditable(false);
        _nsTextField33.setOpaque(false);
        _nsTextField33.setText("Dismiss commands after:");
        _nsTextField33.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField33.setSelectable(false);
        _nsTextField33.setEnabled(true);
        _nsTextField33.setBorder(null);
        _setFontForComponent(_nsTextField32, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField32.setEditable(false);
        _nsTextField32.setOpaque(false);
        _nsTextField32.setText("successful runs");
        _nsTextField32.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField32.setSelectable(true);
        _nsTextField32.setEnabled(true);
        _nsTextField32.setBorder(null);
        _setFontForComponent(_nsTextField31, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField31.setEditable(true);
        _nsTextField31.setOpaque(true);
        _nsTextField31.setText("");
        _nsTextField31.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField31.setSelectable(true);
        _nsTextField31.setEnabled(true);
        _setFontForComponent(_nsTextField30, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField30.setEditable(false);
        _nsTextField30.setOpaque(false);
        _nsTextField30.setText("Repeat commands until:");
        _nsTextField30.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField30.setSelectable(false);
        _nsTextField30.setEnabled(true);
        _nsTextField30.setBorder(null);
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsTextField30.setSize(134, 14);
        _nsTextField30.setLocation(30, 23);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField30, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField30);
        _nsTextField31.setSize(35, 19);
        _nsTextField31.setLocation(164, 20);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField31, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField31);
        _nsTextField32.setSize(87, 14);
        _nsTextField32.setLocation(203, 23);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField32, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField32);
        _nsTextField33.setSize(140, 14);
        _nsTextField33.setLocation(24, 50);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField33, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField33);
        _nsTextField34.setSize(35, 19);
        _nsTextField34.setLocation(164, 47);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField34, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField34);
        _nsTextField35.setSize(44, 14);
        _nsTextField35.setLocation(203, 50);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField35, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField35);
        _nsTextField36.setSize(316, 14);
        _nsTextField36.setLocation(30, 83);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField36, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsTextField36);
        _nsButton1.setSize(106, 17);
        _nsButton1.setLocation(36, 104);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton1);
        _nsButton2.setSize(106, 17);
        _nsButton2.setLocation(145, 104);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton2);
        _nsButton3.setSize(82, 17);
        _nsButton3.setLocation(254, 104);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton3);
        _nsButton4.setSize(106, 17);
        _nsButton4.setLocation(36, 124);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton4);
        _nsButton5.setSize(133, 17);
        _nsButton5.setLocation(145, 124);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton5);
        _nsButton6.setSize(106, 17);
        _nsButton6.setLocation(36, 144);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton6);
        _nsButton7.setSize(133, 17);
        _nsButton7.setLocation(145, 144);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton7);
        _nsButton8.setSize(240, 17);
        _nsButton8.setLocation(36, 164);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView3.add(_nsButton8);
        _setFontForComponent(_nsTextField29, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField29.setEditable(false);
        _nsTextField29.setOpaque(false);
        _nsTextField29.setText("Max per command:");
        _nsTextField29.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField29.setSelectable(false);
        _nsTextField29.setEnabled(true);
        _nsTextField29.setBorder(null);
        _setFontForComponent(_nsTextField28, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField28.setEditable(false);
        _nsTextField28.setOpaque(false);
        _nsTextField28.setText("submissions");
        _nsTextField28.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField28.setSelectable(true);
        _nsTextField28.setEnabled(true);
        _nsTextField28.setBorder(null);
        _setFontForComponent(_nsTextField27, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField27.setEditable(true);
        _nsTextField27.setOpaque(true);
        _nsTextField27.setText("2");
        _nsTextField27.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField27.setSelectable(true);
        _nsTextField27.setEnabled(true);
        _setFontForComponent(_nsTextField26, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField26.setEditable(false);
        _nsTextField26.setOpaque(false);
        _nsTextField26.setText("commands");
        _nsTextField26.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField26.setSelectable(true);
        _nsTextField26.setEnabled(true);
        _nsTextField26.setBorder(null);
        _setFontForComponent(_nsTextField25, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField25.setEditable(true);
        _nsTextField25.setOpaque(true);
        _nsTextField25.setText("10,000");
        _nsTextField25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField25.setSelectable(true);
        _nsTextField25.setEnabled(true);
        _setFontForComponent(_nsTextField24, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField24.setEditable(false);
        _nsTextField24.setOpaque(false);
        _nsTextField24.setText("Max submitted:");
        _nsTextField24.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField24.setSelectable(false);
        _nsTextField24.setEnabled(true);
        _nsTextField24.setBorder(null);
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsTextField24.setSize(100, 14);
        _nsTextField24.setLocation(20, 17);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField24, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField24);
        _nsTextField25.setSize(47, 19);
        _nsTextField25.setLocation(125, 14);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField25, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField25);
        _nsTextField26.setSize(63, 14);
        _nsTextField26.setLocation(177, 17);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField26, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField26);
        _nsTextField27.setSize(30, 19);
        _nsTextField27.setLocation(125, 38);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField27, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField27);
        _nsTextField28.setSize(71, 14);
        _nsTextField28.setLocation(160, 41);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField28, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField28);
        _nsTextField29.setSize(108, 14);
        _nsTextField29.setLocation(12, 42);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField29, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsTextField29);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(302, 71);
        _nsBox3.setLocation(2, 15);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Global limits", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField23, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField23.setEditable(false);
        _nsTextField23.setOpaque(false);
        _nsTextField23.setText("commands");
        _nsTextField23.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField23.setSelectable(true);
        _nsTextField23.setEnabled(true);
        _nsTextField23.setBorder(null);
        _setFontForComponent(_nsTextField22, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField22.setEditable(false);
        _nsTextField22.setOpaque(false);
        _nsTextField22.setText("commands");
        _nsTextField22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField22.setSelectable(true);
        _nsTextField22.setEnabled(true);
        _nsTextField22.setBorder(null);
        _setFontForComponent(_nsTextField21, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField21.setEditable(false);
        _nsTextField21.setOpaque(false);
        _nsTextField21.setText("max:");
        _nsTextField21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField21.setSelectable(false);
        _nsTextField21.setEnabled(true);
        _nsTextField21.setBorder(null);
        _setFontForComponent(_nsTextField20, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField20.setEditable(true);
        _nsTextField20.setOpaque(true);
        _nsTextField20.setText("1,000");
        _nsTextField20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField20.setSelectable(true);
        _nsTextField20.setEnabled(true);
        _setFontForComponent(_nsTextField19, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField19.setEditable(false);
        _nsTextField19.setOpaque(false);
        _nsTextField19.setText("commands");
        _nsTextField19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField19.setSelectable(true);
        _nsTextField19.setEnabled(true);
        _nsTextField19.setBorder(null);
        _setFontForComponent(_nsTextField18, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField18.setEditable(false);
        _nsTextField18.setOpaque(false);
        _nsTextField18.setText("min:");
        _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField18.setSelectable(false);
        _nsTextField18.setEnabled(true);
        _nsTextField18.setBorder(null);
        _setFontForComponent(_nsTextField17, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField17.setEditable(true);
        _nsTextField17.setOpaque(true);
        _nsTextField17.setText("1,000");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField17.setSelectable(true);
        _nsTextField17.setEnabled(true);
        _setFontForComponent(_nsTextField16, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText(" available agents x ");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);
        _setFontForComponent(_nsTextField15, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField15.setEditable(true);
        _nsTextField15.setOpaque(true);
        _nsTextField15.setText("1,000");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField15.setSelectable(true);
        _nsTextField15.setEnabled(true);
        _setFontForComponent(_nsTextField14, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("+");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField14.setSelectable(true);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);
        _setFontForComponent(_nsTextField13, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(true);
        _nsTextField13.setText("");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField13.setSelectable(true);
        _nsTextField13.setEnabled(false);
        _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("bytes");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField12.setSelectable(true);
        _nsTextField12.setEnabled(false);
        _nsTextField12.setBorder(null);
        _setFontForComponent(_nsTextField11, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(true);
        _nsTextField11.setText("10,000,000");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField11.setSelectable(true);
        _nsTextField11.setEnabled(false);
        _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("max size:");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(false);
        _nsTextField10.setBorder(null);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField10.setSize(56, 14);
        _nsTextField10.setLocation(64, 95);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField10);
        _nsTextField11.setSize(71, 19);
        _nsTextField11.setLocation(125, 92);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField11);
        _nsTextField12.setSize(33, 14);
        _nsTextField12.setLocation(200, 95);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField12);
        _nsTextField13.setSize(37, 19);
        _nsTextField13.setLocation(124, 14);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField13);
        _nsTextField14.setSize(13, 14);
        _nsTextField14.setLocation(166, 19);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField14);
        _nsTextField15.setSize(40, 19);
        _nsTextField15.setLocation(184, 16);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField15);
        _nsTextField16.setSize(107, 14);
        _nsTextField16.setLocation(12, 18);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField16);
        _nsTextField17.setSize(40, 19);
        _nsTextField17.setLocation(125, 67);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField17);
        _nsTextField18.setSize(75, 14);
        _nsTextField18.setLocation(45, 70);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField18);
        _nsTextField19.setSize(63, 14);
        _nsTextField19.setLocation(170, 70);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField19, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField19);
        _nsTextField20.setSize(40, 19);
        _nsTextField20.setLocation(125, 41);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField20, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField20);
        _nsTextField21.setSize(31, 14);
        _nsTextField21.setLocation(89, 44);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField21, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField21);
        _nsTextField22.setSize(63, 14);
        _nsTextField22.setLocation(170, 44);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField22, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField22);
        _nsTextField23.setSize(63, 14);
        _nsTextField23.setLocation(229, 19);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField23, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsTextField23);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(302, 125);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Number of commands per submission", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField9.setEditable(true);
        _nsTextField9.setOpaque(true);
        _nsTextField9.setText("");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(true);
        _nsTextField9.setEnabled(true);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("seconds");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField8.setSelectable(true);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Submit new commands every:");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTextField7.setSize(164, 14);
        _nsTextField7.setLocation(25, 17);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField7);
        _nsTextField8.setSize(48, 14);
        _nsTextField8.setLocation(255, 17);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField8);
        _nsTextField9.setSize(56, 19);
        _nsTextField9.setLocation(194, 14);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsTextField9);
        _nsButton0.setSize(141, 15);
        _nsButton0.setLocation(24, 195);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsButton0);
        _nsBox0.setSize(306, 142);
        _nsBox0.setLocation(17, 46);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsBox0);
        _nsBox2.setSize(306, 88);
        _nsBox2.setLocation(17, 226);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView2.add(_nsBox2);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Select the grid(s) to use for submissions:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _eoTableColumn4.setMinWidth(40);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(351);
        _eoTableColumn4.setWidth(351);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("");
        if ((_eoTableColumn4.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn4.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn3.setMinWidth(20);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(25);
        _eoTableColumn3.setWidth(25);
        _eoTableColumn3.setResizable(false);
        _eoTableColumn3.setHeaderValue("");
        if ((_eoTableColumn3.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn3.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView1.table().addColumn(_eoTableColumn3);
        _nsTableView1.table().addColumn(_eoTableColumn4);
        _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView1.table().setRowHeight(20);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTableView1.setSize(384, 273);
        _nsTableView1.setLocation(20, 42);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsTableView1);
        _nsTextField6.setSize(390, 14);
        _nsTextField6.setLocation(18, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsTextField6);
        _setFontForComponent(_nsTextField5, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField5.setEditable(true);
        _nsTextField5.setOpaque(true);
        _nsTextField5.setText("");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField5.setSelectable(true);
        _nsTextField5.setEnabled(true);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Job name:");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("/path/to/the/output/folder");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Output:");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("/path/to/the/input/file");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Input:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(36, 14);
        _nsTextField0.setLocation(44, 42);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField1.setSize(129, 14);
        _nsTextField1.setLocation(79, 42);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField2.setSize(45, 14);
        _nsTextField2.setLocation(35, 64);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField2);
        _nsTextField3.setSize(152, 14);
        _nsTextField3.setLocation(79, 64);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField3);
        _nsTextField4.setSize(61, 14);
        _nsTextField4.setLocation(19, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField4);
        _nsTextField5.setSize(323, 19);
        _nsTextField5.setLocation(82, 17);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField5);
        _nsTabView0.addTab("General", _nsView0);
        _nsTabView0.addTab("Grids", _nsView1);
        _nsTabView0.addTab("Submissions", _nsView2);
        _nsTabView0.addTab("Validation", _nsView3);
        _nsTabView0.addTab("Progress", _nsView4);
        _nsTabView0.addTab("Xgrid jobs", _nsView5);
        if (!(_nsView7.getLayout() instanceof EOViewLayout)) { _nsView7.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(434, 367);
        _nsTabView0.setLocation(11, 14);
        ((EOViewLayout)_nsView7.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView7.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView7.setSize(456, 388);
            _eoFrame1.setTitle("Job Settings");
            _eoFrame1.setLocation(424, 260);
            _eoFrame1.setSize(456, 388);
        }

        if (_replacedObjects.objectForKey("_gridStufferAppDelegate0") == null) {
            _connect(_gridStufferAppDelegate0, _eoFrame1, "metaJobInspectorPanel");
        }

        if (_replacedObjects.objectForKey("_gridStufferAppDelegate0") == null) {
            _connect(_gridStufferAppDelegate0, _arrayController0, "jobArrayController");
        }

        if (_replacedObjects.objectForKey("_gridStufferAppDelegate0") == null) {
            _connect(_gridStufferAppDelegate0, _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _gridStufferAppDelegate0, "delegate");
        }

        _eoTableColumn2.setMinWidth(100);
        _eoTableColumn2.setMaxWidth(100);
        _eoTableColumn2.setPreferredWidth(100);
        _eoTableColumn2.setWidth(100);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Progress");
        if ((_eoTableColumn2.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn2.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn1.setMinWidth(38);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(74);
        _eoTableColumn1.setWidth(74);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Tasks");
        if ((_eoTableColumn1.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn1.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn1.setCellRenderer(renderer);
        }
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }
        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(279);
        _eoTableColumn0.setWidth(279);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Name");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView0.table().addColumn(_eoTableColumn0);
        _nsTableView0.table().addColumn(_eoTableColumn1);
        _nsTableView0.table().addColumn(_eoTableColumn2);
        _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView0.table().setRowHeight(20);
        if (!(_nsView6.getLayout() instanceof EOViewLayout)) { _nsView6.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(480, 409);
        _nsTableView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView6.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView6.add(_nsTableView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView6.setSize(466, 397);
            _eoFrame0.setTitle("Job List");
            _eoFrame0.setLocation(68, 332);
            _eoFrame0.setSize(466, 397);
        }
    }
}
